name: mafia_companion
description: A companion for Tournament Mafia game
publish_to: 'none'
repository: https://github.com/evgfilim1/mafia-companion
issue_tracker: https://github.com/evgfilim1/mafia-companion/issues
version: 0.3.0-rc.2+14

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  async: ^2.11.0
  crypto: ^3.0.3
  dynamic_color: ^1.7.0
  file_picker: ^8.0.0+1
  file_saver: ^0.2.10
  flutter:
    sdk: flutter
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: 786d04363f587b818ce585d25b9c2bb62de95aba
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  intl: ^0.19.0
  material_color_utilities: ^0.8.0
  meta: ^1.11.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  provider: ^6.1.1
  share_plus: ^9.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  uuid: ^4.4.0
  vibration: ^1.8.4
  vibration_web: ^1.6.6  # adds web support for `vibration` package

dependency_overrides:
  # workaround, see https://github.com/material-foundation/flutter-packages/issues/574
  material_color_utilities: ^0.11.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
