name: Build app

on:
  push:
    tags:
      - '*'

env:
  JAVA_VERSION: "11"
  FLUTTER_CHANNEL: "beta"
  PAGES_CNAME: "mafia.evgfilim1.me"

permissions:
  contents: read

jobs:
  build-apk:
    name: Build app for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: "flutter-:os:-:arch:-:version:-:hash:"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build app for Android
        run: flutter build apk --split-per-abi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          if-no-files-found: error
          path: |
            build/app/outputs/flutter-apk/app-*.apk

  build-web:
    name: Build app for web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: "flutter-:os:-:arch:-:version:-:hash:"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build app for web
        run: flutter build web

      - name: Patch app name for web
        run: |
          jq -c '.app_name = "Mafia companion"' build/web/version.json >build/web/version.new.json
          mv build/web/version{.new,}.json

      - name: Upload web artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-bundle
          if-no-files-found: error
          path: build/web

  draft-release:
    name: Draft release
    runs-on: ubuntu-latest
    needs:
      - build-apk
    permissions:
      contents: write
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: android-apk
          path: build

      - name: Draft a release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: true
          files: |
            build/app-*.apk

  publish-web:
    name: Publish web build on GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - build-web
    permissions:
      contents: write
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: web-bundle
          path: web

      - name: Publish web on GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: ${{ env.PAGES_CNAME }}
          publish_dir: web
