name: Run checks for pull request

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ".github/workflows/test-pr.yaml"
      - "lib/**"
      - "test/**"
      - "analysis_options.yaml"
      - "pubspec.lock"
      - "pubspec.yaml"

env:
  JAVA_VERSION: "11"
  FLUTTER_CHANNEL: "beta"

permissions:
  contents: read

jobs:
  test:
    name: Lint and test code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: "flutter-:os:-:arch:-:version:-:hash:"

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Check formatting
        run: dart format --set-exit-if-changed --output none --line-length=100 .

      - name: Run tests
        run: flutter test
